version = 0.1
[default.deploy.parameters]
stack_name = "upnest-percentile"
resolve_s3 = true
s3_prefix = "upnest-percentile"
region = "eu-south-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
